### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by nosraty20200** [OpiumCity/YoutubeViewBotWithProxy#4]
Traceback (most recent call last):
  File "C:\pyton3.8\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\pyton3.8\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\pyton3.8\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\test2\Documents\GitHub\YoutubeViewBotWithProxy\botyoutube.py", line 125, in <module>
    browser_one = webdriver.Chrome(r"C:\Users\Julien MAUCLAIR\Desktop\Bot Youtube\webdriver\chromedriver")
  File "C:\pyton3.8\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\pyton3.8\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

>>>

**Comment by pamiy88391** [comment]
<tr>
					<td><img src="https://software.dbtechlabs.com/images/mytube/ranker/01.png" /></a> </td>
					</tr>
